### PR TITLE
Attempting to solve #35: Synchronization problem causing EXC_BAD_ACCESS and inserting nil into Dictionary during serialization

### PR DESCRIPTION
**Pull request by mark-plukkido**

### CODE REVIEW

**Comment by ptelad** [comment]
Thank you!
Let's hope this does it.

Did you actually caught the dictionary being serialized by several threads?

**Comment by mark-plukkido** [comment]
Not exactly. I suspected that this was due to some synchronization issue because the exception @moret also posted in #35 shows up randomly in `serialize:` in the stack as well. Since NSKeyedArchiver is not thread safe, I started to @synchronize the `serialize:` call. That's when the SIGABRT and additional EXC_BAD_ADDRESS exceptions in the progress delegate function started to pour in (if you continuously tried to keep 200+ downloads in the queue).

Some of those address violations were looking like they target already released memory blocks. Examining the stack and the operations which led to the violation it looked like the RNBackgroundDownloader instance's NSDictionary values were being dereferenced, but those pointers were obviously stale if they cause address violations. So that led me to conclude that some other process deletes the reference from these NSDictionary instances as a mutation operation is in progress on another. These are also instance local, so the only code having access to these are the functions defined in the RNBackgroundDownloader.m file. Therefore I suspected that synchronizing the progress delegate function will likely stop this from happening. Which it did.

Now I think the whole issue could be solved without @synchronize, because I suspect the root cause is that the NSOperationQueue you create for the NSURLSession delegateQueue is not serial. In fact, the default behavior is that the system sets it dynamically based on CPU core load. You have to specify `downloadOperationsQueue.maxConcurrentOperationCount =1;` before the creation of NSURLSession to ensure there are no parallel delegate function calls, ever. I don't have the time to verify this now, so it's up to whoever interested in pursuing the root cause further.

https://developer.apple.com/documentation/foundation/nsoperationqueue/1414982-maxconcurrentoperationcount

**Comment by behealy** [comment]
@mark-plukkido Do you think that simply passing nil for the `delegateQueue` in 
`[NSUrlSession sessionWithConfiguration:delegate:delegateQueue]` Would be a remedy? 

From the [docs for that method](https://developer.apple.com/documentation/foundation/nsurlsession/1411597-sessionwithconfiguration?language=objc):
>The queue should be a serial queue, in order to ensure the correct ordering of callbacks. If nil, the session creates a serial operation queue for performing all delegate method calls and completion handler calls.

It seems, as I think I saw you say elsewhere, that there could be several issues linked to the delegate methods being executed in parallel. One other that comes to mind is: https://github.com/EkoLabs/react-native-background-downloader/issues/31

**Comment by mark-plukkido** [comment]
If the documentation says so, then it will likely have the same effect. I'm not close to my test setup this week, but I'll try to check it next week if nobody else can test it.

**Comment by ptelad** [comment]
I've change the queue to nil in 2.2.0, let's see if it changes anything.
I've also got rid of the urlToConfigMap in favor of saving the taskId->Config map itself

**Pull request merged**
