### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CodeRabbitYu**

### CODE REVIEW

**Comment by ptelad** [comment]
What do you mean by "pure number"?
ID should be a string.

**Comment by CodeRabbitYu** [comment]
@ptelad  if(id === '8f772d9e8e8211e9951600163e04bb2e') ❌，An error 
 "REQUEST_NOT_SUCCESSFUL"

if (id === '123456789')✅， because in `RNBackgroundDownloaderModule.java`, the type of id is ids,
It needs to be a pure number

**Comment by ptelad** [comment]
I have tested your ID in the test app and it works, maybe something else is the problem.

**Comment by CodeRabbitYu** [comment]
@ptelad If the download fails, `RNBackgroundDownloaderModule.java  264 and 265`,Will delete `download.getId()`, but in the onError method, Not getting the right `download.getId()`.

**Comment by ptelad** [comment]
`download.getId()` is a `Fetch` API, and indeed its IDs are numbers and not strings.
This where `requestIdToConfig` comes in as it maps these ids to configs gotten from the JS part that include the original String ID given in the `download` method.

Lines 264 and 265 are for progress reporting and there's no deletion of any ID so I'm not sure what you saw.

**Comment by CodeRabbitYu** [comment]
@ptelad Sorry, My RN version is 0.57, So I use 1.1.0 version.   

image

If the download fails, `Log.d('test', "onError: " + download.getId());`  In onError method, I can't get the right id，  It will be `-111114444`.

**Pull request closed without merging**
